### ISSUE TITLE
When play begins: write file WordGraph Data from Table 1.

### ISSUE THREAD

**Issue by kdabwl** [DavidKinder/Windows-Glulxe#2]
Hello,

and thanks for your effort and the publications. I got the downloaded .exe file to work under Win 11; it looks good and stable.

But where are files stored? I couldn't find a trace. See subject line by which data is stored for (my) later reuse in another story.

With kind regards,
A.B.

P.S. If possible at all please do not store in the directory where the game file was read from, the IDE clears this dir on exit. TX

**Comment by DavidKinder** [comment]
Windows Glulxe writes its data files to the same directory as the game file. But the built-in interpreter in Windows Inform 7 writes it to the Files subdirectory of the Materials folder for the project (if it exists) or just the directory containing the project if not.

For general questions about using Inform 7 you'd probably be better off asking at https://intfiction.org/.

**Comment by kdabwl** [comment]
Thank you for answering my specific question, appreciated it :-)
